# Generated by Django 6.1.1 on 2026-09-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Токен подтверждения email'),
        ),
    ]
